config:
  user-id: "github|81417"
  download-path: "../tmp"
  log-level: debug
  imandra-service:
    command: ["docker", "run", "--interactive", "--rm", "--volume", "/Users:/Users", "quay.io/aestheticintegration/imandra-bin:v0.8a92-5bd323b"]

models:
  fix-engine:
    package:
      path: "."

pipelines:
  dash_and_verify:
    steps:
      - dash:
          description: |
            First pass: dash all the VGs.
          model: fix-engine
          goals:
            - name: app_down_get_biz_reject
              fn-name: app_down_get_biz_reject
              fn-args:
                state: fix_engine_state

            - name: less_seq_num_logout
              fn-name: less_seq_num_logout
              fn-args:
                state: fix_engine_state

            - name: garbled_are_ignored
              fn-name: garbled_are_ignored
              fn-args:
                state: fix_engine_state

            - name: session_rejects_are_rejected
              fn-name: session_rejects_are_rejected
              fn-args:
                state: fix_engine_state

            - name: skipped_heartbeat_causes_logout
              fn-name: skipped_heartbeat_causes_logout
              fn-args:
                state: fix_engine_state

            - name: heartbeat_updated_correctly
              fn-name: heartbeat_updated_correctly
              fn-args:
                state: fix_engine_state

            - name: heartbeat_sent_out_correctly
              fn-name: heartbeat_sent_out_correctly
              fn-args:
                state: fix_engine_state

            - name: last_time_data_sent_gets_updated
              fn-name: last_time_data_sent_gets_updated
              fn-args:
                state: fix_engine_state

            - name: hbeat_sent_if_no_data_received
              fn-name: hbeat_sent_if_no_data_received
              fn-args:
                state: fix_engine_state

            - name: non_grabled_updates_clock
              fn-name: non_grabled_updates_clock
              fn-args:
                state: fix_engine_state

            - name: test_request_sent_out
              fn-name: test_request_sent_out
              fn-args:
                state: fix_engine_state

            - name: no_response_logoff
              fn-name: no_response_logoff
              fn-args:
                state: fix_engine_state

            - name: heartbeat_has_correct_id
              fn-name: heartbeat_has_correct_id
              fn-args:
                test_req_id: int
                state: fix_engine_state

      - verify:
          description: |
            Second pass: verify the VGs that passed the dash step.
          model: fix-engine
